var DEFAULT_TEMPLATE = {
    "TABS": {
        "activeTxtColor": 1602017535,
        "bubbleOn": false,
        "color": -1,
        "height": 1,
        // "id": 126674,
        "isDefaultColor": false,
        "tabId": -1,
        "tabs": [{
                "id": 0,
                "label": "TAB1"
            },
            {
                "id": 0,
                "label": "TAB2"
            },
            {
                "id": 0,
                "label": "TAB3"
            },
            {
                "id": 0,
                "label": "TAB4"
            }
        ],
        "textColor": 255,
        "type": "TABS",
        "underlineColor": 600084223,
        "width": 8,
        "x": 0,
        "y": 0
    },
    "BUTTON": {
        "color": 600084223,
        "deviceId": 0,
        "fontSize": "MEDIUM",
        "height": 2,
        // "id": 52446, 
        "isDefaultColor": true,
        "label": "My Button",
        "max": 1.0,
        "min": 0.0,
        "offLabel": "OFF",
        "onLabel": "ON",
        "pin": 0,
        "pinType": "VIRTUAL",
        "pushMode": false,
        "pwmMode": false,
        "rangeMappingOn": false,
        "tabId": 0,
        "type": "BUTTON",
        "value": "0",
        "width": 2,
        // "x": 0, 
        // "y": 0
    },
    "STEP": {
        "color": 600084223,
        "deviceId": 0,
        "frequency": 100,
        "height": 1,
        // "id": 114453,
        "isArrowsOn": false,
        "isDefaultColor": true,
        "isLoopOn": false,
        "isSendStep": false,
        "max": 1023.0,
        "min": 0.0,
        "pin": -1,
        "pwmMode": false,
        "rangeMappingOn": false,
        "showValueOn": true,
        "step": 1.0,
        "tabId": 1,
        "type": "STEP",
        "width": 4,
        // "x": 4, 
        // "y": 8
    },
    "VERTICAL_STEP": {
        "color": 600084223,
        "deviceId": 0,
        "frequency": 100,
        "height": 2,
        // "id": 24855, 
        "isArrowsOn": false,
        "isDefaultColor": true,
        "isLoopOn": false,
        "isSendStep": false,
        "max": 1023.0,
        "min": 0.0,
        "pin": -1,
        "pwmMode": false,
        "rangeMappingOn": false,
        "showValueOn": true,
        "step": 1.0,
        "tabId": 1,
        "type": "VERTICAL_STEP",
        "width": 2,
        // "x": 5, 
        // "y": 4
    },
    "NUMBER_INPUT": {
        "color": 600084223,
        "deviceId": 0,
        "fontSize": "SMALL",
        "height": 1,
        // "id": 239585795, 
        "isDefaultColor": true,
        "isLoopOn": true,
        "label": "my ",
        "max": 1023.0,
        "min": 0.0,
        "pin": -1,
        "pwmMode": false,
        "rangeMappingOn": false,
        "step": 1.0,
        "tabId": 0,
        "type": "NUMBER_INPUT",
        "width": 4,
        // "x": 0, 
        // "y": 10
    },
    "JOYSTICK": {
        "autoReturnOn": true,
        "color": 600084223,
        "deviceId": 0,
        "frequency": 100,
        "height": 4,
        // "id": 75304, 
        "isDefaultColor": true,
        "pins": [{
                "max": 100.0,
                "min": 0.0,
                "pin": 0,
                "pinType": "VIRTUAL",
                "pwmMode": false,
                "rangeMappingOn": false
            },
            {
                "max": 100.0,
                "min": 0.0,
                "pin": 0,
                "pinType": "VIRTUAL",
                "pwmMode": false,
                "rangeMappingOn": false
            }
        ],
        "portraitLocked": false,
        "split": true,
        "tabId": 2,
        "type": "TWO_AXIS_JOYSTICK",
        "width": 5,
        // "x": 0, 
        // "y": 5
    },
    "RGB": {
        "color": 600084223,
        "deviceId": 0,
        "frequency": 100,
        "height": 3,
        // "id": 111810,
        "isDefaultColor": false,
        "label": "Jjj",
        "pins": [{
                "max": 255.0,
                "min": 0.0,
                "pin": 4,
                "pinType": "VIRTUAL",
                "pwmMode": false,
                "rangeMappingOn": false
            },
            {
                "max": 255.0,
                "min": 0.0,
                "pin": 4,
                "pinType": "VIRTUAL",
                "pwmMode": false,
                "rangeMappingOn": false
            },
            {
                "max": 255.0,
                "min": 0.0,
                "pin": 4,
                "pinType": "VIRTUAL",
                "pwmMode": false,
                "rangeMappingOn": false
            }
        ],
        "sendOnReleaseOn": false,
        "splitMode": false,
        "tabId": 0,
        "type": "RGB",
        "width": 4,
        // "x": 0, 
        // "y": 13
    },
    "LABELED_VALUE_DISPLAY": {
        "color": -750560001,
        "deviceId": 0,
        "fontSize": "LARGE",
        "frequency": 0,
        "height": 1,
        // "id": 182797, 
        "isDefaultColor": false,
        "label": "Hhh",
        "max": 100.0,
        "min": 0.0,
        "pin": 21,
        "pinType": "VIRTUAL",
        "pwmMode": false,
        "rangeMappingOn": false,
        "tabId": 2,
        "textAlignment": "LEFT",
        "type": "LABELED_VALUE_DISPLAY",
        "valueFormatting": "/pin/",
        "width": 4,
        // "x": 0, 
        // "y": 3
    },
    "LED": {
        "color": 600084223,
        "deviceId": 0,
        "height": 2,
        // "id": 199331, 
        "isDefaultColor": true,
        "max": 0.0,
        "min": 0.0,
        "pin": 1,
        "pinType": "VIRTUAL",
        "pwmMode": false,
        "rangeMappingOn": false,
        "tabId": 3,
        "type": "LED",
        "value": "-0.05418396\u00000.21044922\u00009.830338",
        "width": 3,
        // "x": 3, 
        // "y": 3
    },
    "GAUGE": {
        "color": 600084223,
        "deviceId": 0,
        "fontSize": "MEDIUM",
        "frequency": 1000,
        "height": 3,
        // "id": 145412, 
        "isDefaultColor": true,
        "max": 100.0,
        "min": 0.0,
        "pin": -1,
        "pwmMode": false,
        "rangeMappingOn": false,
        "tabId": 1,
        "type": "GAUGE",
        "width": 4,
        // "x": 4, 
        // "y": 10
    },
    "TERMINAL": {
        "attachNewLine": true,
        "autoScrollOn": true,
        "color": 255,
        "deviceId": 0,
        "height": 3,
        // "id": 177756,
        "isDefaultColor": true,
        "max": 0.0,
        "min": 0.0,
        "pin": -1,
        "pwmMode": false,
        "rangeMappingOn": false,
        "tabId": 1,
        "terminalInputOn": false,
        "textLightOn": true,
        "type": "TERMINAL",
        "width": 8,
    },
    "LEVEL_DISPLAY": {
        "color": 600084223,
        "deviceId": 0,
        "frequency": 1000,
        "height": 1,
        // "id": 93731, 
        "isAxisFlipOn": false,
        "isDefaultColor": true,
        "max": 1023.0,
        "min": 0.0,
        "pin": -1,
        "pwmMode": false,
        "rangeMappingOn": false,
        "showValueOn": true,
        "tabId": 3,
        "type": "LEVEL_DISPLAY",
        "width": 3,
        // "x": 0, 
        // "y": 3
    },
    "VERTICAL_LEVEL_DISPLAY": {
        "color": 600084223,
        "deviceId": 0,
        "frequency": 1000,
        "height": 3,
        // "id": 192213,
        "isAxisFlipOn": true,
        "isDefaultColor": true,
        "max": 1023.0,
        "min": 0.0,
        "pin": -1,
        "pwmMode": false,
        "rangeMappingOn": false,
        "showValueOn": true,
        "tabId": 3,
        "type": "VERTICAL_LEVEL_DISPLAY",
        "width": 1,
        // "x": 0,
        // "y": 4
    },
    "CHART": {
        "allowFullScreen": true,
        "color": 600084223,
        "fontSize": "MEDIUM",
        "goalLine": "GOAL",
        "height": 3,
        "hideGradient": false,
        // "id": 54996, 
        "isDefaultColor": true,
        "isPercentMaxMin": false,
        "overrideYAxis": false,
        "period": "LIVE",
        "selectedPeriods": [
            "LIVE",
            "ONE_HOUR",
            "SIX_HOURS",
            "N_DAY",
            "N_WEEK",
            "N_MONTH",
            "N_THREE_MONTHS"
        ],
        "showLegend": true,
        "showTitle": true,
        "showXAxis": false,
        "stacking": "NO_STACKING",
        "tabId": 3,
        "textAlignment": "LEFT",
        "type": "ENHANCED_GRAPH",
        "width": 8,
        // "x": 0, 
        "xAxisValues": false,
        // "y": 10, 
        "yAxisMax": 0.0,
        "yAxisMin": 0.0,
        "yAxisValues": false,
        "dataStreams": []
    },
    "STREAM": {
        "color": 600084223,
        "connectMissingPointsEnabled": true,
        "cubicSmoothingEnabled": false,
        "delta": 0.0,
        "flip": 511,
        "graphType": "LINE",
        "isPercentMaxMin": true,
        "maximumFractionDigits": 1,
        "pin": {
            "max": 100.0,
            "min": 0.0,
            "pin": 2,
            "pinType": "VIRTUAL",
            "pwmMode": false,
            "rangeMappingOn": false
        },
        "showYAxis": true,
        "targetId": 0,
        "title": "My D",
        "userDeltaModifyAllowed": false,
        "yAxisMax": 100000000.0,
        "yAxisMin": 0.0,
        "yAxisScale": "MINMAX"
    },
    "STYLED_BUTTON": {
        "buttonStyle": "OUTLINE",
        "color": 0,
        "deviceId": 0,
        "edge": "PILL",
        "fontSize": "MEDIUM",
        "height": 2,
        // "id": 54951, 
        "isDefaultColor": false,
        "lockSize": false,
        "max": 1.0,
        "min": 0.0,
        "offButtonState": {
            "backgroundColor": 600084223,
            "textColor": -1,
            "text": "OFF"
        },
        "onButtonState": {
            "backgroundColor": 600084223,
            "textColor": 1602017535,
            "text": "ON"
        },
        "pin": -1,
        "pinType": "VIRTUAL",
        "pushMode": true,
        "pwmMode": false,
        "rangeMappingOn": false,
        "tabId": 0,
        "type": "STYLED_BUTTON",
        "value": "0.0",
        "width": 4,
        // "x": 4, 
        // "y": 1
    },
    "SLIDER": {
        "color": 600084223,
        "deviceId": 0,
        "frequency": 200,
        "height": 1,
        // "id": 76394, 
        "isDefaultColor": true,
        "max": 100.0,
        "maximumFractionDigits": 0,
        "min": 0.0,
        "pin": -1,
        "pinType": "VIRTUAL",
        "pwmMode": false,
        "rangeMappingOn": false,
        "sendOnReleaseOn": false,
        "showValueOn": true,
        "tabId": 1,
        "type": "SLIDER",
        "width": 4,
        // "x": 2, 
        // "y": 2
    },
    "VERTICAL_SLIDER": {
        "color": 600084223,
        "deviceId": 0,
        "frequency": 200,
        "height": 3,
        // "id": 112705, 
        "isDefaultColor": true,
        "max": 100.0,
        "maximumFractionDigits": 0,
        "min": 0.0,
        "pin": -1,
        "pinType": "VIRTUAL",
        "pwmMode": false,
        "rangeMappingOn": false,
        "sendOnReleaseOn": false,
        "showValueOn": true,
        "tabId": 1,
        "type": "VERTICAL_SLIDER",
        "width": 1,
    },
}

function LOAD_TEMPLATE(name) {
    return JSON.parse(JSON.stringify(DEFAULT_TEMPLATE[name]))
}